data_root: /sc-projects/sc-proj-cc06-ag-ki-radiologie/prostate_test/COMFORT_data_mpMRI/processed/t2_registered
dataset_json: /sc-scratch/sc-scratch-cc06-ag-ki-radiologie/prostate_foundation/WSAttention-Prostate/dataset/test_data_updated_with_psa.json
num_classes: !!int 4
mil_mode: att_trans
tile_count: !!int 40
tile_size: !!int 48
depth: !!int 3
use_heatmap: !!bool True
workers: !!int 2
checkpoint_cspca: /sc-scratch/sc-scratch-cc06-ag-ki-radiologie/prostate_foundation/WSAttention-Prostate/logs/cspca_train_psa/models/cspca_model_57.pth
batch_size: !!int 8


