data_root: /sc-projects/sc-proj-cc06-ag-ki-radiologie/pirad_model_test_PICAI/processed/t2_registered/
dataset_json: /sc-scratch/sc-scratch-cc06-ag-ki-radiologie/prostate_foundation/WSAttention-Prostate/dataset/PICAI_cspca_updated.json
mil_mode: att_trans
tile_count: !!int 40
tile_size: !!int 48
depth: !!int 3
use_heatmap: !!bool True
workers: !!int 2
checkpoint_pirads: /sc-scratch/sc-scratch-cc06-ag-ki-radiologie/prostate_foundation/WSAttention-Prostate/logs/pirads_training_new/model_44.pt
epochs: !!int 80
batch_size: !!int 8
optim_lr: !!float 2e-5
num_seeds: !!int 5




