data_root:
dataset_json: /sc-scratch/sc-scratch-cc06-ag-ki-radiologie/prostate_foundation/WSAttention-Prostate/dataset/cspca_train.json
num_classes: !!int 4
mil_mode: att_trans
tile_count: !!int 40
tile_size: !!int 48
depth: !!int 3
use_heatmap: !!bool True
workers: !!int 2
checkpoint_cspca: /sc-scratch/sc-scratch-cc06-ag-ki-radiologie/prostate_foundation/WSAttention-Prostate/logs/cspca_train_randmodel_newtrain_tcia/models/cspca_model_71.pth
num_seeds: !!int 10 
batch_size: !!int 8


